name: Build

on:
  push:
    tags:
      - "*"

env:
  BUILD_NUMBER: ${{ github.tag }}
  PROJECT_NAME: "Flashlight"
  PROJECT_PATH: "./Flashlight/Flashlight.csproj"
  OUTPUT_PATH: "./Flashlight/Flashlight"
  PUBLISH_PATH: "./Flashlight/Flashlight"


jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} -c Flashlight -o ${{ env.OUTPUT_PATH }}

  publish:
    if: github.event_name == 'push'
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} -c Flashlight -o ${{ env.OUTPUT_PATH }}
      - name: Clean files
        run: |
          rm -f \
            ${{ env.OUTPUT_PATH }}/Flashlight.deps.json \
            ${{ env.OUTPUT_PATH }}/Flashlight.pdb \
      - name: Zip
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: '${{ env.PROJECT_NAME }}.zip'
          path: ${{ env.PUBLISH_PATH }}
      - name: GunGameLite
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "${{ env.PROJECT_NAME }}.zip"
          name: "${{ env.BUILD_NUMBER }}"
          tag: "${{ env.BUILD_NUMBER }}"
          body: |
            Place the plugin in game/csgo/addons/counterstrikesharp/plugins/Flashlight